version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: banco-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SqlServer@123"
    ports:
      - "1433:1433"
    volumes:
      - banco_sqlserver_data:/var/opt/mssql

volumes:
  banco_sqlserver_data: